---
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: restarted