---
galaxy_info:
  author: DevOps Team
  description: Common system setup and configuration
  company: Todo API Project
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - system
    - common
    - setup

dependencies: []