version: '3.8'

services:
  # MongoDB Database Service - Staging Configuration
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb-staging
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: todoapi-staging
    volumes:
      - mongodb_staging_data:/data/db
      - mongodb_staging_config:/data/configdb
    networks:
      - todo-staging-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.15'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Todo API Service - Staging Configuration
  todo-api:
    image: ${DOCKER_IMAGE_TAG:-todo-api:staging}
    container_name: todo-api-staging
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: staging
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/todoapi-staging
      DB_NAME: todoapi-staging
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE:-10}
      DB_SERVER_SELECTION_TIMEOUT: ${DB_SERVER_SELECTION_TIMEOUT:-5000}
      DB_SOCKET_TIMEOUT: ${DB_SOCKET_TIMEOUT:-45000}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      ENABLE_DEBUG_ROUTES: ${ENABLE_DEBUG_ROUTES:-true}
      NODE_OPTIONS: "--max-old-space-size=256"
    networks:
      - todo-staging-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.15'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

# Named volumes for data persistence
volumes:
  mongodb_staging_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./staging-data}/mongodb
  mongodb_staging_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./staging-data}/mongodb-config

# Staging network configuration
networks:
  todo-staging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16