version: '3.8'

services:
  # MongoDB Database Service - Production Configuration
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todoapi
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # Security: Don't expose MongoDB port to host in production
    # ports:
    #   - "27017:27017"

  # Todo API Service - Production Configuration
  todo-api:
    image: ${DOCKER_IMAGE_TAG:-todo-api:latest}
    container_name: todo-api-prod
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/todoapi
      DB_NAME: todoapi
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE:-20}
      DB_SERVER_SELECTION_TIMEOUT: ${DB_SERVER_SELECTION_TIMEOUT:-5000}
      DB_SOCKET_TIMEOUT: ${DB_SOCKET_TIMEOUT:-45000}
      # Production optimizations
      NODE_OPTIONS: "--max-old-space-size=512"
    networks:
      - todo-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # Security: Run as non-root user
    user: "1000:1000"

# Named volumes for data persistence
volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/mongodb
  mongodb_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/mongodb-config

# Production network configuration
networks:
  todo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    driver_opts:
      com.docker.network.bridge.name: todo-prod-br0