---
galaxy_info:
  author: DevOps Team
  description: Install and configure Docker and Docker Compose
  company: Todo API Project
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - containers
    - deployment

dependencies: []